//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.Describe
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisteredControl
    {
        public int RegisterControlID { get; set; }
        public string table_catalog { get; set; }
        public string table_schema { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string container_name { get; set; }
        public string control_name { get; set; }
    }
}
