//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlProperty
    {
        public int RegsisterControlID { get; set; }
        public int RegisterPropertyID { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<int> PropertValueID { get; set; }
    }
}
