//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupAddr
    {
        public int GroupID { get; set; }
        public int AddrID { get; set; }
        public bool PrimaryAddrID { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual tblGroup tblGroup { get; set; }
        public virtual tblVolAddress tblVolAddress { get; set; }
    }
}
