//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroup
    {
        public tblGroup()
        {
            this.tblVolAddresses = new HashSet<tblVolAddress>();
            this.tblVolunteers = new HashSet<tblVolunteer>();
        }
    
        public int GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ParticipationLevelID { get; set; }
        public Nullable<bool> ActiveFlg { get; set; }
        public byte[] Photo { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<tblVolAddress> tblVolAddresses { get; set; }
        public virtual ICollection<tblVolunteer> tblVolunteers { get; set; }
    }
}
