//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectEvent
    {
        public tblProjectEvent()
        {
            this.tblEventRatings = new HashSet<tblEventRating>();
            this.tblProjectEventContacts = new HashSet<tblProjectEventContact>();
        }
    
        public System.Guid EventID { get; set; }
        public System.Guid ProjectID { get; set; }
        public Nullable<System.DateTime> StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> AddrID { get; set; }
    
        public virtual ICollection<tblEventRating> tblEventRatings { get; set; }
        public virtual ICollection<tblProjectEventContact> tblProjectEventContacts { get; set; }
    }
}
