//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSampleContact
    {
        public tblSampleContact()
        {
            this.tblSampleAddresses = new HashSet<tblSampleAddress>();
        }
    
        public int ContactID { get; set; }
        public string ContactName { get; set; }
    
        public virtual ICollection<tblSampleAddress> tblSampleAddresses { get; set; }
    }
}
