//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVolunteer
    {
        public tblVolunteer()
        {
            this.tblVolEmails = new HashSet<tblVolEmail>();
            this.tblSkills = new HashSet<tblSkill>();
            this.tblAvailabilities = new HashSet<tblAvailability>();
            this.tblVolAddrs = new HashSet<tblVolAddr>();
            this.tblGroups = new HashSet<tblGroup>();
        }
    
        public System.Guid VolID { get; set; }
        public Nullable<bool> ActiveFlg { get; set; }
        public string VolFirstName { get; set; }
        public string VolMiddleName { get; set; }
        public string VolLastName { get; set; }
    
        public virtual ICollection<tblVolEmail> tblVolEmails { get; set; }
        public virtual ICollection<tblSkill> tblSkills { get; set; }
        public virtual ICollection<tblAvailability> tblAvailabilities { get; set; }
        public virtual ICollection<tblVolAddr> tblVolAddrs { get; set; }
        public virtual ICollection<tblGroup> tblGroups { get; set; }
    }
}
