//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendorAddr
    {
        public System.Guid VendorID { get; set; }
        public int AddrID { get; set; }
        public Nullable<bool> HQ { get; set; }
    
        public virtual tblVendAddress tblVendAddress { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
