//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVolState
    {
        public int StateID { get; set; }
        public string name { get; set; }
        public string abbreviation { get; set; }
        public string country { get; set; }
        public string type { get; set; }
        public Nullable<int> sort { get; set; }
        public string status { get; set; }
        public string occupied { get; set; }
        public string notes { get; set; }
        public string fips_state { get; set; }
        public string assoc_press { get; set; }
        public string standard_federal_region { get; set; }
        public string census_region { get; set; }
        public string census_region_name { get; set; }
        public string census_division { get; set; }
        public string census_devision_name { get; set; }
        public string circuit_court { get; set; }
    }
}
