//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendor
    {
        public tblVendor()
        {
            this.tblVendContacts = new HashSet<tblVendContact>();
            this.tblVendorAddrs = new HashSet<tblVendorAddr>();
            this.tblVendorProjContacts = new HashSet<tblVendorProjContact>();
        }
    
        public System.Guid VendorID { get; set; }
        public string VendorName { get; set; }
        public Nullable<int> ActiveFlg { get; set; }
    
        public virtual ICollection<tblVendContact> tblVendContacts { get; set; }
        public virtual ICollection<tblVendorAddr> tblVendorAddrs { get; set; }
        public virtual ICollection<tblVendorProjContact> tblVendorProjContacts { get; set; }
    }
}
