//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVendEmail
    {
        public tblVendEmail()
        {
            this.tblContactEmails = new HashSet<tblContactEmail>();
        }
    
        public int EmailID { get; set; }
        public string EmailAddr { get; set; }
        public bool ActiveFlg { get; set; }
    
        public virtual ICollection<tblContactEmail> tblContactEmails { get; set; }
    }
}
