//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VolTeer.DataAccessLayer.VT
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_CheckConstraints
    {
        public string Table_Catalog { get; set; }
        public string Table_Schema { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public string constraint_catalog { get; set; }
        public string Constraint_name { get; set; }
        public string check_clause { get; set; }
    }
}
